---
- import_playbook: "Hardening_Ubuntu.yml"
- import_playbook: "Ensure Automatic Error Reporting is configured.yml"
- import_playbook: "Ensure Inactive Password Lock is configured.yml"
- import_playbook: "Ensure Sudo Logfile Exists.yml"
- import_playbook: "Ensure dccp kernel module is not available.yml"
- import_playbook: "Ensure default user umask is configured.yml"
- import_playbook: "Ensure firewire-core kernel module is not available.yml"
- import_playbook: "Ensure ftp client is not installed.yml"
- import_playbook: "Ensure journald Storage is configured.yml"
- import_playbook: "Ensure mail transfer agents are configured for local-only mode.yml"
- import_playbook: "Ensure net.ipv4.conf.all.accept_redirects is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.all.rp_filter is configured.yml"
- import_playbook: "Ensure net.ipv4.conf.default.rp_filter is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.all.accept_ra is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.all.accept_redirects is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.all.accept_source_route is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.all.forwarding is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.default.accept_ra is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.default.accept_redirects is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.default.accept_source_route is configured.yml"
- import_playbook: "Ensure net.ipv6.conf.default.forwarding is configured.yml"
- import_playbook: "Ensure pam_faillock module is enabled.yml"
- import_playbook: "Ensure pam_pwhistory includes use_authtok.yml"
- import_playbook: "Ensure pam_pwhistory module is enabled.yml"
- import_playbook: "Ensure pam_unix does not include nullok.yml"
- import_playbook: "Ensure password expiration is configured.yml"
- import_playbook: "Ensure password failed attempts lockout is configured.yml"
- import_playbook: "Ensure password history is enforced for the root user.yml"
- import_playbook: "Ensure password history remember is configured.yml"
- import_playbook: "Ensure password quality is enforced for the root user.yml"
- import_playbook: "Ensure password unlock time is configured.yml"
- import_playbook: "Ensure randomize_va_space is configured.yml"
- import_playbook: "Ensure rds kernel module is not available.yml"
- import_playbook: "Ensure sctp kernel module is not available.yml"
- import_playbook: "Ensure tipc kernel module is not available.yml"
- import_playbook: "Ensure tmp is in separate partition.yml"
